name: hello-world
on: push
jobs:
  setup-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
    test-job:
      needs: setup-job
      - run: make test
      - run: make lint
      